# Generated by Django 4.1 on 2022-08-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_post_author_post_authorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authorId',
            new_name='author',
        ),
    ]
